### PR TITLE
silence "not a git repository" console message.

### PR DESCRIPTION
**Pull request by veksha**

### CODE REVIEW

**Comment by veksha** [comment]
What kind of issues?

**Comment by CudaText-addons** [comment]
I dont know - any issues, which break the work.

**Comment by veksha** [comment]
no. do you have any?
I still have freezes sometimes when Cud starts, especially when terminal+ is autostarting (and git_status is loading info)
I think it's connected to this problem: https://stackoverflow.com/questions/72432659/two-popen-processes-are-colliding-in-python-3-6-8?noredirect=1#comment127958154_72432659
but i'm not sure.

sometimes popen in git_status code wants to wait until terminal popen's cmd.exe will close. (but terminal needs cmd.exe to be alive).

**Comment by Alexey-T** [comment]
Quote from stackover

AFAIK, communicate() has threads that pump I/O streams. And it should not block when you are only reading Output. Python 3.10 works. I just want to know if there is a workaround for 3.6.

so you can install package for Py 3.10 and try it?

**Comment by veksha** [comment]
I can't reproduce it reliably in Cud.
how can I change the order in which addons are loading? is it random?

**Comment by CudaText-addons** [comment]
it is ordered by ASCII sorting of module names: cuda_aaa before cuda_bb.

**Comment by CudaText-addons** [comment]
also, we can change priority of plugins. in the install.inf:
https://wiki.freepascal.org/CudaText_API#Events_priority

**Comment by veksha** [comment]
```ini
[bottombar1]
hint=Terminal+
icon={dir}/terminal.png
method=open
```

Terminal+ is loading itself from this event (or it's rather not an event). what is priority of this bottombar1.open method?

**Comment by CudaText-addons** [comment]
it's not an event! it's command binding ! event is configured in the 'events=' line.

**Comment by veksha** [comment]
try to execute this 3 lines inside Cud Console (you must do it on Windows):
```python
import threading; from time import sleep; from subprocess import Popen, PIPE, STDOUT
def run(): print('thread'); p2 = Popen('git', stdin = PIPE, stdout = PIPE, stderr = PIPE); o,e = p2.communicate(); print('thread.popen/communicate')
threading.Thread(target=run, daemon=True).start(); p1 = Popen('cmd', stdin = PIPE, stdout = PIPE, stderr = STDOUT); print('main.popen'); sleep(2)
```
it's the same code from my stackoverflow question.
notice how in python 3.6 we see `thread.popen/communicate` line printed only when you close cmd.exe window. that means one process is waiting for another for some reason.

In other python versions (3.7+) this line is printed immediately!! you don't need to close cmd.exe to make it happen.
try it.

All I can think of is this can be a bug with python 3.6, that is fixed in 3.7+

can't reproduce bug on 3.7. I use automated test like this:
.cmd script (.bat) that will run Cud forever.
```bat
:start
cudatext.exe
goto start
```

and temporarily added os._exit after TIMER_STOP to cuda_git_status/__init__.py:
like this:
```python
    timer_proc(TIMER_STOP, TIMERCALL, 0)
    os._exit(0)
```

now Cud will open and close forever, until it encounters bug. in this case it will freeze. (be sure to set up all preconditions we talked about, so processes of git and terminal, (and LSP) can collide on Cud's start and one will wait for closing of another)

**Comment by CudaText-addons** [comment]
let's continue in the Cud #4160.

**Pull request merged**
