### PR TITLE
added another error check "you need to resolve index"

### PR DESCRIPTION
**Pull request by veksha**
happens when there is unresolved merge conflict and you are trying to switch to another branch.

### CODE REVIEW

**Comment by Alexey-T** [comment]
can we check `if text.startswith('error: ') or text.startswith('fatal: ')`
?
instead of these long strings?

**Comment by veksha** [comment]
```python
'fatal: ' in error_text or
'error: ' in error_text
```
I see no problem with this.

**Comment by veksha** [comment]
wait. something is wrong. :)
i'll check.

**Comment by CudaText-addons** [comment]
my POV:
text `error: ` can  happed inside the commit messages like `fixed my app error: hhhhhhhhhhh`.
it in the middle of the line.

**Comment by veksha** [comment]
> my POV: text `error: ` can happed inside the commit messages like `fixed my app error: hhhhhhhhhhh`. in the middle of the line.

in stderr?

**Comment by veksha** [comment]
OK. lets test it for a while. seems ok.

**Comment by veksha** [comment]
```
NOTE: Git Status:  fatal: ambiguous argument 'origin/test...test': unknown revision or path not in the working tree.
```
this console message will appear when we try to get `unpushed_info` (while switching branch) and origin/test branch is not yet exists for test branch.

one solution is to silence errors for certain functions using new argument `silenceErrors`:
```python
def run_git(self, args, silenceErrors=False):
```

**Comment by veksha** [comment]
or redirect stderr: `2>nul` or `2>/dev/null`

**Comment by Alexey-T** [comment]
Please use pythonic_case, not camelCaseNames. Also nice to fix this case in recent patch from you.

Yes, we can silence errors for some actions, ok

**Comment by Alexey-T** [comment]
Redirect stderr- are sure it will work on all BSD OSes? On Solaris? On Haiku?

**Comment by veksha** [comment]
> Redirect stderr- are u sure it will work on all BSD OSes? On Solaris? On Haiku?

no. i'm not 100% sure. i'm only familiar with Windows/Linux.

**Comment by Alexey-T** [comment]
Then let’s ignore error_text only , patch welcome

**Pull request merged**
